// Entry point for the build script in your package.json
console.log("hello.....");
import "@hotwired/turbo-rails"
// import "./controllers"
import "jquery"
// // import "../assets/stylesheets/application.css"
import "./custom"
import "./google_tag"
// "vendors/scripts/core.js"
import "./scripts/core.js"
// "vendors/scripts/script.min"
import "./scripts/script.min.js"
// "vendors/scripts/process"
import "./scripts/process.js"
// "vendors/scripts/layout-settings"
import "./scripts/layout-settings.js"
// "src/plugins/jQuery-Knob-master/jquery.knob.min"
import "./plugins/jQuery-Knob-master/jquery.knob.min.js"
// "src/plugins/highcharts-6.0.7/code/highcharts"
import "./plugins/highcharts-6.0.7/code/highcharts.js"
// "src/plugins/highcharts-6.0.7/code/highcharts-more"
import "./plugins/highcharts-6.0.7/code/highcharts-more.js"
// "src/plugins/jvectormap/jquery-jvectormap-2.0.3.min"
import "./plugins/jvectormap/jquery-jvectormap-2.0.3.min.js"
// "src/plugins/jvectormap/jquery-jvectormap-world-mill-en"
import "./plugins/jvectormap/jquery-jvectormap-world-mill-en.js"
// "vendors/scripts/dashboard2"
import "./scripts/dashboard2.js"

import "@shoelace-style/shoelace/dist/components/button/button.js"
import "@shoelace-style/shoelace/dist/components/icon/icon.js"
import "@shoelace-style/shoelace/dist/components/spinner/spinner.js"